### ISSUE TITLE
train！

### ISSUE THREAD

**Issue by hankaitai** [royerlab/cytoself#17]
hi！
I have a few problems with training.
I tried to get the final model parameters myself when reproducing the code, but the results were terrible. So I want to know how many epochs you trained to get the final result.
At the same time, the amount of data for this work is for me, so can I only use proteins with a single first level localization information for training? This will make my attempt much easier.

**Comment by li-li-github** [comment]
Hi, The example script is only to demonstrate how to run the code. The sample data provided in the example is too small that you won't be able to get decent results. Please train on more data from [Data Availability](https://github.com/royerlab/cytoself#data-availability).

**Comment by hankaitai** [comment]
Thank you for your reply.
Fortunately, I have achieved good results in recent days.
