### ISSUE TITLE
The difference between tensorflow and pytorch version

### ISSUE THREAD

**Issue by exogeny** [royerlab/cytoself#19]
In the **tensorflow** version: decoder using `qtvec` as inputs.
But in the pytorch version, using `encoded` as inputs instead of `qtvec`.

May you provide some explanation about this difference?

**Comment by li-li-github** [comment]
hmm... Do you mean that in the PyTorch version, the outputs of encoders are directly passed to the decoders whereas in the tensor flow version, the outputs of VectorQuantization layers are passed to the decoders?
Yeah, indeed a good point. It might be a mistake. It should be the quantized tensors that are passed to the decoders.

**Comment by li-li-github** [comment]
I have fixed the issue in #20. lmk if that has addressed your question.
