### ISSUE TITLE
Packages missing + embedding_dim is required for vq_args

### ISSUE THREAD

**Issue by sheryllin111** [royerlab/cytoself#28]
I ran into two errors while trying to run the sample analysis. I had the same issue as Dedy (https://github.com/royerlab/cytoself/issues/26) but fixed this by downloading the cytoself folder from the github, then installing the additional dependencies. I now have this error while trying to run CytoselfFullTrainer:
![image](https://github.com/royerlab/cytoself/assets/73864698/e6bea39d-2d9e-4ebb-81f5-2e7085bf9b2f)
![image](https://github.com/royerlab/cytoself/assets/73864698/e55f2d5e-596f-4df6-883e-e2db26d5de41)

**Comment by li-li-github** [comment]
Hi @sheryllin111 The main branch of cytoself is now implemented with PyTorch but the pip package has not been updated. So you need to follow [the instruction for developers](https://github.com/royerlab/cytoself#for-the-developers-install-from-this-repository) to install cytoself from the repository. 

For the error you've got, it looks like you have duplicated keyword argument 'vq_args' in your script. You shouldn't get the error if you only use the first 'vq_args' that has the value `{'num_embeddings': 512, 'embedding_dim': 64}`.
