### ISSUE TITLE
Labels that don't match up with available images

### ISSUE THREAD

**Issue by amulyagarimella** [royerlab/cytoself#36]
Hi! I'm using OpenCell data + Cytoself for a project, and want to use the provided label data to look up original images. However, I'm having some trouble matching the labels to their original images (in AWS).
For example, I have the following label:
```
ensg: ENSG00000038358
name: EDC4
loc_grade1: vesicles
loc_grade2:  NaN
loc_grade3: cytoplasmic
protein_id: 830
FOV_id: 2883
```

But there's no image with this FOV ID in the [s3 bucket](https://czb-opencell.s3.amazonaws.com/index.html#microscopy/raw/EDC4_ENSG00000038358/):
<img width="554" alt="Screenshot 2024-01-18 at 11 15 59 AM" src="https://github.com/royerlab/cytoself/assets/8853022/ffad96df-280c-4c8d-bd36-27a02a2bf260">

I'd appreciate any guidance on how to appropriately use the labels to find original images. Thanks so much.

**Comment by amulyagarimella** [comment]
by the way I'm currently solving this by referencing the entire concatenated image numpy object by index, but would love to be able to check the original images on AWS!

**Comment by li-li-github** [comment]
Hi @amulyagarimella 
The FOV id indicates different fields of view. I don't remember exactly but looking at the file names, I guess it's probably the last 4 digits of FID0000xxxx. I think this S3 buck only offers image data to the [opencell protal](https://opencell.czbiohub.org) and doesn't contain all the data used in cytoself. The numpy data offered in this repo is the most complete cytoself image data as far as I know.

**Comment by amulyagarimella** [comment]
OK, no worries, so it's probably just that those images with those FOVs are not available in the opencell portal.
