### ISSUE TITLE
Setup of full .npy dataset?

### ISSUE THREAD

**Issue by amulyagarimella** [royerlab/cytoself#37]
Hi! I wanted to ask about the setup of the full npy dataset and how each image relates to the labels. There are ~9-10 images per label. Are they in order corresponding to labels (e.g. first 9 images corresponds to first label) or is there some other setup structure?

Thanks so much!

**Comment by li-li-github** [comment]
Hi @amulyagarimella, labels and image are in the same order in the original data. The first image data in  [Image_data00.npy](https://drive.google.com/file/d/15_CHBPT-p5JG44acP6D2hKd8jAacZatp/view?usp=sharing) corresponds to the first label in  [Label_data00.csv](https://drive.google.com/file/d/1CVwvXW2KhVBbTBixwRXIIiMhrlGDXz-4/view?usp=sharing) for example. This default order is the only way to find the image-label correspondence.

**Comment by amulyagarimella** [comment]
OK that makes sense, thank you!
