### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by JacobNeumann88** [royerlab/cytoself#5]
Hello, when attempting to use the demo py file I get an error that the modules
" 
cytoself.data_loader.data_manager import DataManager
from cytoself.models import CytoselfFullModel
from cytoself.data_loader.data_generator import image_and_label_generator
from cytoself.analysis.analytics import Analytics"

Do not exist.

**Comment by li-li-github** [comment]
Have you checked if you were using the right environment that cytoself is installed?
If the issue still persists even after you reinstall everything in a clean environment, could you try installing cytoself from this repository? 
https://github.com/royerlab/cytoself#for-developers

**Comment by rouarouatbi** [comment]
Hey, I am also getting installation issues, even though I did use the correct environment.
Cloning from git doesn't seem to work either

**Comment by li-li-github** [comment]
What issues did you get? Have you tried [cytoself-pytorch](https://github.com/royerlab/cytoself/tree/cytoself-pytorch) branch? There may be some issues with cuda version if you use TF1.15 with newer GPUs. This pytorch version will be the mian branch.

**Comment by li-li-github** [comment]
The cytoself-pytorch is now on the main branch!

**Comment by rouarouatbi** [comment]
It works! Thank you :)
