### ISSUE TITLE
Code about Nucleus Segmentation

### ISSUE THREAD

**Issue by Yuangaga** [royerlab/cytoself#6]
Hi, very nice job!

Could I reference the **code about nucleus segmentation** mentioned in your NM article? I can't find it in this repository.

Thanks.

**Comment by li-li-github** [comment]
Hi, I'm sorry for the late reply.
The code mentioned in the article is [this](https://gist.github.com/li-li-github/fccb54605b2ce94df41e350ea296691b) but I would recommend using [StarDist](https://github.com/stardist/stardist).
Its pre-trained model `2D_versatile_fluo` works better and is more flexible to various image data than our hardcoded algorithm.

**Comment by Yuangaga** [comment]
Thank you very much for your help. I'll try it. ^_^
